imdb.o: imdb.cc imdb.h imdb-utils.h
imdb-unit-test.o: imdb-unit-test.cc imdb.h imdb-utils.h
imdb.o: imdb.cc imdb.h imdb-utils.h
path.o: path.cc path.h imdb-utils.h
six-degrees.o: six-degrees.cc imdb.h imdb-utils.h path.h
